trigger: none

pool:
  vmImage: ubuntu-latest

stages:

- stage: Build
  displayName: Build

  jobs:
  - job: BuildJob
    steps:
    - script: |
        echo "Build stage started"
        echo "Build completed"
      displayName: Build


- stage: Terraform
  displayName: Terraform
  dependsOn: Build

  jobs:
  - job: TerraformJob

    steps:

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: latest

    - task: AzureCLI@2
      displayName: Terraform Init Plan Apply
      inputs:
        azureSubscription: 'q25-secure-azure'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          cd q26-terraform

          echo "Terraform Init"
          terraform init

          echo "Terraform Plan"
          terraform plan

          echo "Terraform Apply"
          terraform apply -auto-approve

          echo "Terraform Output"

          VM_NAME=$(terraform output -raw vm_name)

          echo "VM Name: $VM_NAME"

          echo "##vso[task.setvariable variable=vmName;isOutput=true]$VM_NAME"


- stage: Helm
  displayName: Helm Deploy
  dependsOn: Terraform
  condition: succeeded()

  variables:
    vmNameFromTerraform: $[ stageDependencies.Terraform.TerraformJob.outputs['terraformOutput.vmName'] ]

  jobs:
  - job: HelmJob
    displayName: Helm Deployment

    steps:

    - script: |
        echo "Terraform succeeded."
        echo "VM Name from Terraform: $(vmNameFromTerraform)"
      displayName: Show Terraform Output

    - script: |
        echo "Current directory:"
        pwd

        echo "Repository contents:"
        find . -maxdepth 4 -type f | sort

        echo "Searching for Chart.yaml:"
        find . -name Chart.yaml -print
      displayName: Find Helm Chart