trigger: none

pool:
  vmImage: ubuntu-latest

stages:

# -------------------------
# Stage 1: Build
# -------------------------
- stage: Build
  displayName: Build

  jobs:
  - job: BuildJob
    displayName: Build application

    steps:
    - script: |
        echo "Build stage started"
        echo "Application build completed"
      displayName: Build


# -------------------------
# Stage 2: Terraform
# -------------------------
- stage: Terraform
  displayName: Terraform
  dependsOn: Build

  jobs:
  - job: TerraformJob
    displayName: Terraform Init Plan Apply

    steps:

    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'

    - task: AzureCLI@2
      displayName: Terraform Init Plan Apply
      inputs:
        azureSubscription: 'q25-secure-azure'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          cd q26-terraform

          echo "Terraform Init"
          terraform init

          echo "Terraform Plan"
          terraform plan

          echo "Terraform Apply"
          terraform apply -auto-approve

          echo "Terraform Outputs"
          terraform output


# -------------------------
# Stage 3: Helm
# -------------------------
- stage: Helm
  displayName: Helm Deploy
  dependsOn: Terraform
  condition: succeeded()

  jobs:
  - job: HelmJob
    displayName: Helm Deployment

    steps:
    - script: |
        echo "Terraform succeeded."
        echo "Starting Helm deployment..."
        echo "Helm deployment completed successfully."
      displayName: Helm Deploy